apiVersion: v1
kind: Service
metadata:
  name: argocd-server
  namespace: argocd
  labels:
    app: argocd-server
spec:
  type: LoadBalancer
  ports:
    - port: 80
      targetPort: 8080
      protocol: TCP
      name: http
#    - port: 443
 #     targetPort: 8080
  #    protocol: TCP
   #   name: https
  selector:
    app: argocd-server
