apiVersion: apps/v1
kind: Deployment
metadata:
  name: test-deploy
  labels:
    app: demo-pod
spec:
  replicas: 1
  selector:
    matchLabels:
      app: demo-pod
  template:
    metadata:
      labels:
        app: test-demo
    spec:
      containers:
      - name: yogik001/test
        image: image: yogik001/test:v1
        ports:
        - containerPort: 80
