apiVersion: apps/v1
kind: Deployment
metadata:
  name:  hello-word
  namespace: default
  labels:
    app:  hello-word
spec:
  selector:
    matchLabels:
      app: hello-word
  replicas: 1
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      labels:
        app:  hello-word
    spec:
      containers:
      - name:  hello-word
        image: yogik001/test:v1
        resources:
          requests:
            cpu: 100m
            memory: 100Mi
          limits:
            cpu: 100m
            memory: 100Mi
        ports:
        - containerPort:  80
          name:  hello-word
      restartPolicy: Always

      