apiVersion: v1
kind: Service
metadata:
  name: hello-word
  namespace: default
spec:
  selector:
    app: hello-word
  type: ClusterIP
  ports:
  - name: hello-word
    protocol: TCP
    port: 80
    targetPort: 80

