apiVersion: v1
kind: Service
metadata:
  name: apache-deployment-argo
  namespace: default
spec:
  selector:
    app: apache-deployment-argo
  type: ClusterIP
  ports:
  - name: apache-deployment-argo
    protocol: TCP
    port: 80
    targetPort: 80
