apiVersion: v1
kind: Service
metadata:
  name: hello-1
  namespace: default
spec:
  selector:
    app: hello-1
  type: ClusterIP
  ports:
  - name: hello-1
    protocol: TCP
    port: 80
    targetPort: 80
