apiVersion: v1
kind: Service
metadata:
  name: apache
  namespace: default
spec:
  selector:
    app: apache
  type: ClusterIP
  ports:
  - name: apache
    protocol: TCP
    port: 80
    targetPort: 80
