apiVersion: apps/v1
kind: Deployment
metadata:
  name:  apache-deployment
  namespace: default
  labels:
    app:  apache-deployment
spec:
  selector:
    matchLabels:
      app: apache-deployment
  replicas: 1
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      labels:
        app:  apache-deployment
    spec:
      containers:
      - name:  apache-deployment
        image: httpd:alpine3.20
        resources:
          requests:
            cpu: 100m
            memory: 100Mi
          limits:
            cpu: 100m
            memory: 100Mi
        ports:
        - containerPort:  80
          name:  apache-deployment
      restartPolicy: Always